default:
  interruptible: true

# Prevent duplicate pipelines
# https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

include:
  - component: $CI_SERVER_FQDN/ci-components/julia/cache@1
  - component: $CI_SERVER_FQDN/ci-components/julia/runtests@1
    inputs:
      versions:
        - "1.6"
        - "1.10"
        - "1"
