name = "MORwiki"
uuid = "0a23ce7c-1a84-4bdb-9995-3360bf4da96c"
authors = ["Jonas Schulze <jschulze@mpi-magdeburg.mpg.de>"]
version = "0.1.0"

[deps]
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
unzip_jll = "88f77b66-78eb-5ed0-bc16-ebba0796830d"

[compat]
DataDeps = "0.7.13"
unzip_jll = "6"
