name = "MORwiki"
uuid = "0a23ce7c-1a84-4bdb-9995-3360bf4da96c"
authors = ["Jonas Schulze <jschulze@mpi-magdeburg.mpg.de>"]
version = "0.1.1"

[deps]
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixMarket = "4d4711f2-db25-561a-b6b3-d35e7d4047d3"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
unzip_jll = "88f77b66-78eb-5ed0-bc16-ebba0796830d"

[compat]
DataDeps = "0.7.13"
DocStringExtensions = "0.9"
MatrixMarket = "0.4, 0.5"
UnPack = "1"
unzip_jll = "6"
